# Black Code Formatter Configuration
# Automatic Python code formatting

[tool.black]
# Target Python versions
target-version = ['py310', 'py311', 'py312']

# Maximum line length
line-length = 88

# Files to include
include = '\.pyi?$'

# Files and directories to exclude
extend-exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | env
    | \.env
    | _build
    | buck-out
    | build
    | dist
    | node_modules
    | __pycache__
    | \.pytest_cache
    | htmlcov
    | \.coverage
  )/
)
'''

# Force single quotes
skip-string-normalization = false

# Preview features
preview = false

# Safe mode
safe = true
